### ISSUE TITLE
Typo in tutorial

### ISSUE THREAD

**Issue by tlsaeger** [davidwarrington/nuxt-tweet#1]
Hi David, thanks for creating this awesome and detailed tutorial. 
I think there is a typo in chapter 5 
``` JS
const dotenv = require(‘dotenv’)
dotenv.config()
```
I guess the quotes are wrong, aren't they?
```JS
const dotenv = require('dotenv')
dotenv.config()
```

**Comment by davidwarrington** [comment]
@tlsaeger Thanks for reporting this, and good spot! I've resolved it now.

Hope the tutorial was otherwise helpful? 😄

**Comment by tlsaeger** [comment]
It was crazy how on point it was on what I was looking for. So thanks again, and thanks for the quick fix!
